### ISSUE TITLE
Q. What will this translation cover as time goes on?

### ISSUE THREAD

**Issue by jt1399** [SciresM/FireEmblemSoVTextTranslation#3]
It's ok if this isn't going to but I'm curious if this will come to cover the story text some time after menu translation is done. Please take your time and don't feel rushed or pushed by this, it's not what I intend with this.

**Comment by SciresM** [comment]
I highly doubt it will ever contain story text. If someone wants to translate it, it's on github for a reason, but, uh, the US game releases in a month.

**Comment by jt1399** [comment]
figured, I just can't wait to play, well, time to wait for the english release or if/when the na version leaks, I am curious whether pkmn moon had it's cia leaked from a cart that was meant to be sold in the us, eu, jp, or somewhere else, just wondering where it came from in general, although it's probably unknown
