### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by GaaraOmega** [SciresM/FireEmblemSoVTextTranslation#4]
Not sure if I'm doing something wrong, I'm on the latest Luma nightly and the patch isn't working.

**Comment by ghost** [comment]
Can you attach a photo of your SD card and do you have Patch svc/service access and Enable game patching enabled on the luma setting menu?

**Comment by GaaraOmega** [comment]
I have the settings enabled.

![f7ef6e6f9699572ba1b3c75e3eb60a79](https://cloud.githubusercontent.com/assets/27042247/24825562/844dd998-1bd5-11e7-8a56-68a7651745c8.png)
![794a1846f0990fd22eb45875090db3d1](https://cloud.githubusercontent.com/assets/27042247/24825559/843ee280-1bd5-11e7-8af8-b0444fa2abbe.png)
![136fb8a7cace7e0c41fb3e18afd6188f](https://cloud.githubusercontent.com/assets/27042247/24825560/8440a098-1bd5-11e7-8aee-982e80e4b742.png)
![4a75dfdb92de1560cfea15d4fc96e630](https://cloud.githubusercontent.com/assets/27042247/24825561/84414f7a-1bd5-11e7-81a4-2fcf1eb60d6c.png)
![029df1b18e73322d981222420c5310d1](https://cloud.githubusercontent.com/assets/27042247/24825563/8453da14-1bd5-11e7-9499-2ff182caa7d9.png)

**Comment by ghost** [comment]
I might not be looking close enough but it seems you only have the salty-sd file. From my experience you need to extract both of the files from the zip to the root of your sd card and it should work. If it doesn't, idk how to help you.

**Comment by ghost** [comment]
Nevermind, I just realized you do have it. Idk how to help you then. My best guess is that it's something else on your sd card interfering with it but I don't know what.

**Comment by GaaraOmega** [comment]
I guess I solved it myself. The language was set to Chinese.

**Comment by SciresM** [comment]
Ha, glad to see this was resolved before I saw it.
